    using System;
    using UnityEngine;
    using UnityEngine.InputSystem;

    public class GameInput : MonoBehaviour
    {

        
        public static GameInput Instance { get; private set; }
        
        
        public event EventHandler OnInteractAction;
        public event EventHandler OnInteractAlternateAction;
        public event EventHandler OnPauseAction;
        
        private PlayerInputActions playerInputActions;

        public enum Binding
        {
            Move_Up,
            Move_Down,
            Move_Left,
            Move_Right,
            Interact,
            InteractAlternate,
            Pause,
        }
        private void Awake() {
            Instance = this;
            playerInputActions = new PlayerInputActions();
            playerInputActions.Player.Enable();

            playerInputActions.Player.Interact.performed += Interact_performed;
            playerInputActions.Player.InteractAlternate.performed += InteractAlternate_performed;
            playerInputActions.Player.Pause.performed += Pause_Performed;

            Debug.Log(GetBindingText(Binding.Interact));
        }

        private void OnDestroy()
        {
            playerInputActions.Player.Interact.performed -= Interact_performed;
            playerInputActions.Player.InteractAlternate.performed -= InteractAlternate_performed;
            playerInputActions.Player.Pause.performed -= Pause_Performed;
            
            playerInputActions.Dispose();
        }
        
        private void Pause_Performed(UnityEngine.InputSystem.InputAction.CallbackContext obj) {
            OnPauseAction?.Invoke(this, EventArgs.Empty);    
        }

        private void InteractAlternate_performed(UnityEngine.InputSystem.InputAction.CallbackContext obj) {
            OnInteractAlternateAction?.Invoke(this, EventArgs.Empty);    
        }
        private void Interact_performed(UnityEngine.InputSystem.InputAction.CallbackContext obj) {
            OnInteractAction?.Invoke(this, EventArgs.Empty);    
        }
        public Vector2 GetMovementVectorNormalized() {
            Vector2 inputVector = playerInputActions.Player.Move.ReadValue<Vector2>();

            inputVector = inputVector.normalized;
            
            return inputVector;    
        }

        public string GetBindingText(Binding binding)
        {
            switch (binding)
            {
                default:
                case Binding.Move_Up:
                    return playerInputActions.Player.Move.bindings[1].ToDisplayString();
                case Binding.Move_Down:
                    return playerInputActions.Player.Move.bindings[2].ToDisplayString();
                case Binding.Move_Left:
                    return playerInputActions.Player.Move.bindings[3].ToDisplayString();
                case Binding.Move_Right:
                    return playerInputActions.Player.Move.bindings[4].ToDisplayString();
                case Binding.Interact:
                    return playerInputActions.Player.Interact.bindings[0].ToDisplayString();
                case Binding.InteractAlternate:
                    return playerInputActions.Player.InteractAlternate.bindings[0].ToDisplayString();
                case Binding.Pause:
                    return playerInputActions.Player.Pause.bindings[0].ToDisplayString();
            }
        }

        public void RebindBinding(Binding binding)
        {
            playerInputActions.Player.Disable();

            playerInputActions.Player.Move.PerformInteractiveRebinding(1)
                .OnComplete(callback =>
                {
                    Debug.Log(callback.action.bindings[1].path);
                    Debug.Log(callback.action.bindings[1].overridePath);
                    playerInputActions.Player.Enable();
                })
                .Start();
        }
    }
